export enum TourCategoryType {
    ENTERTAINMENT = "ENTERTAINMENT",
    CULINARY = "CULINARY",
    EDUCATION = "EDUCATION",
    NATURE = "NATURE",
    CULTURE_HISTORY = "CULTURE_HISTORY",
    RELIGI = "RELIGI",
    ADVENTURE = "ADVENTURE",
    HEALTH = "HEALTH",
}
